///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestCalculator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The calculate recording.
    /// </summary>
    [TestModule("585c8a2e-4763-4588-ac50-e9729963a0ae", ModuleType.Recording, 1)]
    public partial class calculate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestCalculatorRepository repository.
        /// </summary>
        public static TestCalculatorRepository repo = TestCalculatorRepository.Instance;

        static calculate instance = new calculate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public calculate()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static calculate Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Num1Button' at 47;23.", repo.Calculator.Num1ButtonInfo, new RecordItemIndex(0));
            repo.Calculator.Num1Button.Click("47;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Num2Button' at 51;28.", repo.Calculator.Num2ButtonInfo, new RecordItemIndex(1));
            repo.Calculator.Num2Button.Click("51;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.PlusButton' at 12;30.", repo.Calculator.PlusButtonInfo, new RecordItemIndex(2));
            repo.Calculator.PlusButton.Click("12;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Num9Button' at 53;30.", repo.Calculator.Num9ButtonInfo, new RecordItemIndex(3));
            repo.Calculator.Num9Button.Click("53;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Num9Button' at 53;30.", repo.Calculator.Num9ButtonInfo, new RecordItemIndex(4));
            repo.Calculator.Num9Button.Click("53;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Num9Button' at 53;30.", repo.Calculator.Num9ButtonInfo, new RecordItemIndex(5));
            repo.Calculator.Num9Button.Click("53;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.EqualButton' at 50;18.", repo.Calculator.EqualButtonInfo, new RecordItemIndex(6));
            repo.Calculator.EqualButton.Click("50;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.MemPlus' at 36;9.", repo.Calculator.MemPlusInfo, new RecordItemIndex(7));
            repo.Calculator.MemPlus.Click("36;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Num1Button' at 56;15.", repo.Calculator.Num1ButtonInfo, new RecordItemIndex(8));
            repo.Calculator.Num1Button.Click("56;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Num9Button' at 48;6.", repo.Calculator.Num9ButtonInfo, new RecordItemIndex(9));
            repo.Calculator.Num9Button.Click("48;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.PlusButton' at 51;13.", repo.Calculator.PlusButtonInfo, new RecordItemIndex(10));
            repo.Calculator.PlusButton.Click("51;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.MemRecall' at 35;8.", repo.Calculator.MemRecallInfo, new RecordItemIndex(11));
            repo.Calculator.MemRecall.Click("35;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.EqualButton' at 59;14.", repo.Calculator.EqualButtonInfo, new RecordItemIndex(12));
            repo.Calculator.EqualButton.Click("59;14");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
