///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestCalculator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestCalculatorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("b7da740d-fb14-4bce-9017-a7b2d5d64d19")]
    public partial class TestCalculatorRepository : RepoGenBaseFolder
    {
        static TestCalculatorRepository instance = new TestCalculatorRepository();
        TestCalculatorRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the TestCalculatorRepository element repository.
        /// </summary>
        [RepositoryFolder("b7da740d-fb14-4bce-9017-a7b2d5d64d19")]
        public static TestCalculatorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestCalculatorRepository() 
            : base("TestCalculatorRepository", "/", null, 0, false, "b7da740d-fb14-4bce-9017-a7b2d5d64d19", ".\\RepositoryImages\\TestCalculatorRepositoryb7da740d.rximgres")
        {
            _calculator = new TestCalculatorRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b7da740d-fb14-4bce-9017-a7b2d5d64d19")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("86a22205-1f76-46d9-bd43-2645e76df2aa")]
        public virtual TestCalculatorRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class TestCalculatorRepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("86a22205-1f76-46d9-bd43-2645e76df2aa")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _num1buttonInfo;
            RepoItemInfo _plusbuttonInfo;
            RepoItemInfo _num2buttonInfo;
            RepoItemInfo _num9buttonInfo;
            RepoItemInfo _equalbuttonInfo;
            RepoItemInfo _memplusInfo;
            RepoItemInfo _memrecallInfo;
            RepoItemInfo _calculatorresultsInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "86a22205-1f76-46d9-bd43-2645e76df2aa", "")
            {
                _num1buttonInfo = new RepoItemInfo(this, "Num1Button", "button[@automationid='num1Button']", 30000, null, "97cda50e-adad-40e2-b29f-5cf981c135fc");
                _plusbuttonInfo = new RepoItemInfo(this, "PlusButton", "button[@automationid='plusButton']", 30000, null, "91aee6a7-8adc-478c-82c2-f25a6c3add30");
                _num2buttonInfo = new RepoItemInfo(this, "Num2Button", "button[@automationid='num2Button']", 30000, null, "1dbb3d14-f8cb-4cb7-ae72-6fff1c591b04");
                _num9buttonInfo = new RepoItemInfo(this, "Num9Button", "button[@automationid='num9Button']", 30000, null, "487249b3-441f-4882-b07c-b7bda3052404");
                _equalbuttonInfo = new RepoItemInfo(this, "EqualButton", "button[@automationid='equalButton']", 30000, null, "4d6a9da4-b0c7-42f4-bdb5-11b360eeecb8");
                _memplusInfo = new RepoItemInfo(this, "MemPlus", "button[@automationid='MemPlus']", 30000, null, "cd9b0b17-ebaf-4a8f-ae19-0b99f56f7e6f");
                _memrecallInfo = new RepoItemInfo(this, "MemRecall", "button[@automationid='MemRecall']", 30000, null, "3082c8a2-e1c5-4e13-8bc9-09af130c31b9");
                _calculatorresultsInfo = new RepoItemInfo(this, "CalculatorResults", "text[@automationid='CalculatorResults']", 30000, null, "c9e0fbc9-ac56-4a35-baef-0e85a26f2391");
                _closeInfo = new RepoItemInfo(this, "Close", "button[@automationid='Close']", 30000, null, "75c99360-f133-4a87-845d-679a23dfb350");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("86a22205-1f76-46d9-bd43-2645e76df2aa")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("86a22205-1f76-46d9-bd43-2645e76df2aa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Num1Button item.
            /// </summary>
            [RepositoryItem("97cda50e-adad-40e2-b29f-5cf981c135fc")]
            public virtual Ranorex.Button Num1Button
            {
                get
                {
                    return _num1buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num1Button item info.
            /// </summary>
            [RepositoryItemInfo("97cda50e-adad-40e2-b29f-5cf981c135fc")]
            public virtual RepoItemInfo Num1ButtonInfo
            {
                get
                {
                    return _num1buttonInfo;
                }
            }

            /// <summary>
            /// The PlusButton item.
            /// </summary>
            [RepositoryItem("91aee6a7-8adc-478c-82c2-f25a6c3add30")]
            public virtual Ranorex.Button PlusButton
            {
                get
                {
                    return _plusbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PlusButton item info.
            /// </summary>
            [RepositoryItemInfo("91aee6a7-8adc-478c-82c2-f25a6c3add30")]
            public virtual RepoItemInfo PlusButtonInfo
            {
                get
                {
                    return _plusbuttonInfo;
                }
            }

            /// <summary>
            /// The Num2Button item.
            /// </summary>
            [RepositoryItem("1dbb3d14-f8cb-4cb7-ae72-6fff1c591b04")]
            public virtual Ranorex.Button Num2Button
            {
                get
                {
                    return _num2buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num2Button item info.
            /// </summary>
            [RepositoryItemInfo("1dbb3d14-f8cb-4cb7-ae72-6fff1c591b04")]
            public virtual RepoItemInfo Num2ButtonInfo
            {
                get
                {
                    return _num2buttonInfo;
                }
            }

            /// <summary>
            /// The Num9Button item.
            /// </summary>
            [RepositoryItem("487249b3-441f-4882-b07c-b7bda3052404")]
            public virtual Ranorex.Button Num9Button
            {
                get
                {
                    return _num9buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num9Button item info.
            /// </summary>
            [RepositoryItemInfo("487249b3-441f-4882-b07c-b7bda3052404")]
            public virtual RepoItemInfo Num9ButtonInfo
            {
                get
                {
                    return _num9buttonInfo;
                }
            }

            /// <summary>
            /// The EqualButton item.
            /// </summary>
            [RepositoryItem("4d6a9da4-b0c7-42f4-bdb5-11b360eeecb8")]
            public virtual Ranorex.Button EqualButton
            {
                get
                {
                    return _equalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EqualButton item info.
            /// </summary>
            [RepositoryItemInfo("4d6a9da4-b0c7-42f4-bdb5-11b360eeecb8")]
            public virtual RepoItemInfo EqualButtonInfo
            {
                get
                {
                    return _equalbuttonInfo;
                }
            }

            /// <summary>
            /// The MemPlus item.
            /// </summary>
            [RepositoryItem("cd9b0b17-ebaf-4a8f-ae19-0b99f56f7e6f")]
            public virtual Ranorex.Button MemPlus
            {
                get
                {
                    return _memplusInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MemPlus item info.
            /// </summary>
            [RepositoryItemInfo("cd9b0b17-ebaf-4a8f-ae19-0b99f56f7e6f")]
            public virtual RepoItemInfo MemPlusInfo
            {
                get
                {
                    return _memplusInfo;
                }
            }

            /// <summary>
            /// The MemRecall item.
            /// </summary>
            [RepositoryItem("3082c8a2-e1c5-4e13-8bc9-09af130c31b9")]
            public virtual Ranorex.Button MemRecall
            {
                get
                {
                    return _memrecallInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MemRecall item info.
            /// </summary>
            [RepositoryItemInfo("3082c8a2-e1c5-4e13-8bc9-09af130c31b9")]
            public virtual RepoItemInfo MemRecallInfo
            {
                get
                {
                    return _memrecallInfo;
                }
            }

            /// <summary>
            /// The CalculatorResults item.
            /// </summary>
            [RepositoryItem("c9e0fbc9-ac56-4a35-baef-0e85a26f2391")]
            public virtual Ranorex.Text CalculatorResults
            {
                get
                {
                    return _calculatorresultsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CalculatorResults item info.
            /// </summary>
            [RepositoryItemInfo("c9e0fbc9-ac56-4a35-baef-0e85a26f2391")]
            public virtual RepoItemInfo CalculatorResultsInfo
            {
                get
                {
                    return _calculatorresultsInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("75c99360-f133-4a87-845d-679a23dfb350")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("75c99360-f133-4a87-845d-679a23dfb350")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}